# Generated by Django 4.0.4 on 2022-04-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_like_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
