# Generated by Django 4.0.4 on 2022-04-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_followers_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
