# Generated by Django 4.0.4 on 2022-04-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_item_listings_comments_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
