# Generated by Django 4.0.4 on 2022-04-26 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment_listing_alter_bid_item_alter_bid_leader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='item',
        ),
        migrations.AddField(
            model_name='bid',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='listingBids', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
