# Generated by Django 4.0.4 on 2022-04-26 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_bid_endtime_remove_bid_item_bid_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biddingLeaders', to=settings.AUTH_USER_MODEL),
        ),
    ]
