# Generated by Django 4.0.4 on 2022-04-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_bid_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='closed',
        ),
        migrations.AddField(
            model_name='listing',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
