# Generated by Django 4.0.4 on 2022-05-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_user_age_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=0, upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x7ff7970e5b20>'),
            preserve_default=False,
        ),
    ]
